// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLUOlqeetN80ahXjl1T8xWzjJnvOZf4PY',
    appId: '1:486013101298:web:39331c227f2aa44730dc6b',
    messagingSenderId: '486013101298',
    projectId: 'testproject-d7784',
    authDomain: 'testproject-d7784.firebaseapp.com',
    databaseURL: 'https://testproject-d7784-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-d7784.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAWxO8PJTjn8aBUbMnY5uKgSia7CdCxc',
    appId: '1:486013101298:android:66ec421802afb9a030dc6b',
    messagingSenderId: '486013101298',
    projectId: 'testproject-d7784',
    databaseURL: 'https://testproject-d7784-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-d7784.firebasestorage.app',
  );
}
